"""You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        
        # hash the s string

        hash_s = {}

        for char in s:
            if char in hash_s:
                hash_s[char] += 1
            else:
                hash_s[char] = 1

        
        # now iterate through the t string and check if the char is in the hash_s

        for char in t:
            if char not in hash_s:
                return char
            else:
                hash_s[char] -= 1
                if hash_s[char] < 0:
                    return char
                
        return None
    
    # time complexity O(n)
    # space complexity O(n)


    def findTheDifference(self, s: str, t: str) -> str:

        # logic is find the sum of the ascii values of the t string and subtract the sum of the ascii values of the s string

        sum_t = 0
        sum_s = 0

        for char in t:
            sum_t += ord(char)

        for char in s:

            sum_s += ord(char)


        return chr(sum_t - sum_s)
    
    # time complexity O(n)
    # space complexity O(1)
    

